CREATE ROLE administrator LOGIN PASSWORD 'admin_pass' SUPERUSER;
CREATE ROLE operator LOGIN PASSWORD 'operator_pass';
CREATE ROLE client LOGIN PASSWORD 'client_pass';

CREATE DATABASE hotelBooking;

GRANT CONNECT ON DATABASE hotelBooking TO operator, client;
GRANT CREATE ON DATABASE hotelBooking TO operator;

CREATE SCHEMA hotel;
GRANT USAGE ON SCHEMA hotel TO operator;
GRANT CREATE ON SCHEMA hotel TO operator;

GRANT USAGE ON SCHEMA hotel TO operator, client;

GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA hotel TO operator;
GRANT SELECT ON ALL TABLES IN SCHEMA hotel TO client;

ALTER DEFAULT PRIVILEGES IN SCHEMA hotel GRANT SELECT, INSERT, UPDATE ON TABLES TO operator;
ALTER DEFAULT PRIVILEGES IN SCHEMA hotel GRANT SELECT ON TABLES TO client;